baseURL = "https://ngrid.me/blog/"
languageCode = "en-us"
title = "Nicks Blog"
publishDir = "docs"
theme = "fuji"
# theme = "solar-theme-hugo"
# googleAnalytics = "UA-123456789-1"
# disqusShortname = "yourdiscussshortname"
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Hi i am a developer from another dimension, ive come to rock your code"
  homeMetaContent = "Will you see this message, or will the message see you? "
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5